### ISSUE TITLE
No such file or directory: 'data/dataset/trainlist.txt

### ISSUE THREAD

**Issue by kapitsa2811** [sumanmichael/attention-ocr-pytorch#1]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    dm.setup()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/datamodule.py", line 384, in wrapped_fn
    return fn(*args, **kwargs)
  File "/content/attention-ocr-pytorch/src/attention_ocr.py", line 102, in setup
    self.train_dataset = dataset.ListDataset(list_file=self.train_list)
  File "/content/attention-ocr-pytorch/src/utils/dataset.py", line 13, in __init__
    with open(list_file, encoding="utf-8") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'data/dataset/trainlist.txt

**Comment by sumanmichael** [comment]
@kapitsa2811, data is not included in this repo. 
FYI, data/dataset/trainlist.txt looks like

    /path/to/file1 label1
    /path/to/file2 label2
    
make a note that, filename and labels are separated with space.
